### ISSUE TITLE
bring back Monoid-based folds

### ISSUE THREAD

**Issue by wookietreiber** [functional-streams-for-scala/fs2-cats#1]
What fs2-core currently is missing are the Monoid-based fold operations (feel free to edit if I missed some):
- [x] foldMap
- [x] foldMonoid
- [x] foldSemigroup
- [x] runFoldMap

These would have to be implemented here, as fs2-core apparently does not include cats.

**Comment by mpilquist** [comment]
:+1:

@wookietreiber Are you planning on putting a PR together for this? If not, I can do so some point this week.

**Comment by wookietreiber** [comment]
I certainly will try. However, I don't have the slightest idea yet about the internals of fs2, whether I would need to implement these in terms of the internal algebra, or if I could base these on something like [Stream.fold](https://github.com/functional-streams-for-scala/fs2/blob/bcde479ffac46735b3914d895980dcd92a5e1956/core/src/main/scala/fs2/StreamPipeOps.scala#L46) or [Stream.runFold](https://github.com/functional-streams-for-scala/fs2/blob/bcde479ffac46735b3914d895980dcd92a5e1956/core/src/main/scala/fs2/Stream.scala#L23), etc.

**Comment by mpilquist** [comment]
Gotcha. These functions can all be implemented in terms of `stream.fold` and `stream.runFold`. So you'll want something like this in the `fs2.interop.cats` package object:

```
implicit class StreamCatsOps[F[_], A](val self: Stream[F, A]) extends AnyVal {
  def foldMap[B: Monoid](f: A => B): Stream[F, B] = self.fold(...)
}
```

**Comment by wookietreiber** [comment]
Great, thanks for nudging me in the right direction. I think, I will have the PR ready today or tomorrow.
