### ISSUE TITLE
support cats 1.0.0-MF

### ISSUE THREAD

**Issue by SethTisue** [functional-streams-for-scala/fs2-cats#20]
this will eventually be needed in order to keep fs2-cats in the Scala community build, which we want to move from cats 0.9 to 1.0 as soon as reasonably possible (https://github.com/scala/community-builds/issues/549)

**Comment by mpilquist** [comment]
Fixed in f4187599a0005c078deb0514c0648bc1f86d6fe3

**Comment by SethTisue** [comment]
thanks Michael!
